# Generated by Django 5.0.2 on 2024-03-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='mail',
        ),
    ]
