# Generated by Django 5.0.2 on 2024-03-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mundos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mundos',
            name='imagen',
            field=models.ImageField(upload_to='media/mundos'),
        ),
    ]
